config/routes.rb
Rails.application.routes.draw do
  resources :survivors 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   root to: "static_pages#index"

   get '/abducted/:id', to: 'survivors#abducted', as: 'abducted'
   get  'reports', to: 'static_pages#reports'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survivor.rb
class Survivor < ApplicationRecord
    before_update :check_abductedcount

    private

    def check_abductedcount
        
        self.abducted = true if self.abductedcount >= 3
    end    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

        def index
        end
        
        def reports
        end
end

app/controllers/survivors_controller.rb
class SurvivorsController < ApplicationController
  before_action :set_survivor, only: [:show, :edit, :update, :destroy, :abducted]

  # GET /survivors
  # GET /survivors.json
  def index
    @survivors = Survivor.order(name: :asc)
  end

  # GET /survivors/1
  # GET /survivors/1.json
  def show
  end

  # GET /survivors/new
  def new
    @survivor = Survivor.new
  end

  # GET /survivors/1/edit
  def edit
  end

  # POST /survivors
  # POST /survivors.json
  def create
    @survivor = Survivor.new(survivor_params)

    respond_to do |format|
      if @survivor.save
        format.html { redirect_to @survivor, notice: 'Survivor was successfully created.' }
        format.json { render :show, status: :created, location: @survivor }
      else
        format.html { render :new }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survivors/1
  # PATCH/PUT /survivors/1.json
  def update
    respond_to do |format|
      if @survivor.update(survivor_params)
        format.html { redirect_to @survivor, notice: 'Survivor was successfully updated.' }
        format.json { render :show, status: :ok, location: @survivor }
      else
        format.html { render :edit }
        format.json { render json: @survivor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survivors/1
  # DELETE /survivors/1.json
  def destroy
    @survivor.destroy
    respond_to do |format|
      format.html { redirect_to survivors_url, notice: 'Survivor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def abducted
    if @survivor.increment!(:abductedcount)
      redirect_to @survivor, notice: 'Survivor abducted count was incremented.' 
    else
      render :show
    end
  end 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survivor
      @survivor = Survivor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survivor_params
      params.require(:survivor).permit(:name, :age, :gender, :latitude, :longitude)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/survivors_helper.rb
module SurvivorsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'X-SUNIT(Extraterrestrial Survival Unit)', root_url, class: 'navbar-brand' %>
      <%= link_to 'List of survivors', survivors_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav navbar-right">

    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XSunit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/header' %>
     <div class="container">
      <%= yield %>
      </div> 
</html>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Welcome, Survivors</h1>


    
<p> Please registrate or update your location here!</p>
<%= link_to 'Survivors Registrations', new_survivor_path, class: 'btn btn-primary btn-lg' %>


<p></p>
<p> Verify about the survivors situation:</p>
<%= link_to 'Reports', reports_path, class: 'btn btn-primary btn-lg' %>


<p></p>

<p> Be Careful.</p>

</div>

app/views/static_pages/reports.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Reports</h1>

<p> <%= link_to 'List of survivors', survivors_path %></p>

</div>

app/views/survivors/_form.html.erb
<%= form_with(model: survivor, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/survivors/edit.html.erb
<h1>Editing Survivor</h1>

<%= render 'form', survivor: @survivor %>

<%= link_to 'Show', @survivor %> |
<%= link_to 'Back', survivors_path %>

app/views/survivors/index.html.erb
<div class="row">
<div class="col-xs-12 text-center">

<h1>Survivors</h1>
 </div>

 <div class="col-md-8 col-md-offset-2 col-xs-12">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Abducted</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @survivors.each do |survivor| %>
      <tr>
        <td><%= survivor.name %></td>
        <td><%= survivor.age %></td>
        <td><%= survivor.gender %></td>
        <td><%= survivor.latitude %></td>
        <td><%= survivor.longitude %></td>
        <td><%= survivor.abducted %></td>
        <td><%= link_to 'Show', survivor %></td>
        <td><%= link_to 'Edit', edit_survivor_path(survivor) %></td>
        <td><%= link_to 'Destroy', survivor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/survivors/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>New Survivor</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @survivor do |f| %>
      <%= render 'form', survivor: @survivor %>
    <% end %>
  </div>
</div>

<%= link_to 'Back', root_url %>

app/views/survivors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @survivor.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @survivor.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @survivor.gender %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @survivor.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @survivor.longitude %>
</p>

<strong>Abducted:</strong>
  <%= @survivor.abducted %>



<%= link_to 'Edit', edit_survivor_path(@survivor) %> |
<%= link_to 'Back', survivors_path %> |
<%= link_to 'Mark as Abducted', abducted_path(@survivor) %>